### ISSUE TITLE
Ask for help about a simple test.

### ISSUE THREAD

**Issue by Ji-Peng** [fmlab-iis/cryptoline#4]
When the post-condition is ` true  &&  tmp=zmm5_000`, the verification is OK. However, when the post-condition is `tmp=zmm5_000 && true`, the verification is failed.
Why???

```
proc main (uint64 a00, uint64 b00) =
{
  true
  &&
  and [
        a00 <u 0x00fffffffffffff@64, b00 <u 0x00fffffffffffff@64
      ]
}

(* zmm4_000 = a00 + b00 *)
add zmm4_000 a00 b00;
assert zmm4_000=a00+b00 && true;

(* zmm1_000 = (a00+b00)>>51 *)
split zmm1_000 tmp zmm4_000 51; 
assert zmm1_000*(2**51)+tmp=zmm4_000 && true;

(* zmm5 = (a00 + b00) & (2**51 - 1) *)
and zmm5_000@uint64 zmm4_000@uint64 0x0007ffffffffffff@uint64;

{
  true
  &&
  tmp=zmm5_000
}

(*
  true
  &&
  tmp=zmm5_000

  tmp=zmm5_000
  &&
  true
*)
```

**Comment by fuyu0425** [comment]
left-hand side of `&&` is checked by an algebra solver.
`and zmm5_000@uint64 zmm4_000@uint64 0x0007ffffffffffff@uint64;` can not be translated to an algebraic equation; that's why it fails. However, it can be checked by an SMT solver (right-hand side).
